CREATE TABLE cart (
id SERIAL PRIMARY KEY,
user_id INTEGER REFERENCES yourmoon_user(id) ON DELETE CASCADE NOT NULL,
item_id INTEGER REFERENCES items(id) ON DELETE CASCADE NOT NULL,
cart_qty NUMERIC CHECK (cart_qty <= 10), 
date_created TIMESTAMPTZ NOT NULL DEFAULT NOW()
);