CREATE TABLE cart (
cart_id SERIAL PRIMARY KEY,
user_id INTEGER REFERENCES yourmoon_user(id) ON DELETE CASCADE NOT NULL,
item_id INTEGER REFERENCES items(id) ON DELETE CASCADE NOT NULL,
date_created TIMESTAMPTZ NOT NULL DEFAULT NOW()
);