CREATE TABLE cart_item(
    id SERIAL PRIMARY KEY,
    qty INTEGER,
    item_id INTEGER REFERENCES items(id) ON DELETE CASCADE NOT NULL,
    cart_id INTEGER REFERENCES cart(id) ON DELETE CASCADE NOT NULL
);